### ISSUE TITLE
I can't get the player deduction grids to come up

### ISSUE THREAD

**Issue by ChazKat** [LokiMidgard/tragedy-looper-deduction-tool#1]
Could you check up on this project at all? I'd like to use it but it doesn't seem like it's working

**Comment by LokiMidgard** [comment]
Do you mean the player aid?
for me it is working. what do you see if you go to following link: [Player Aid](https://lokimidgard.github.io/tragedy-looper-deduction-tool/player/?set=Another+Horizon&cast=Boy+Student&cast=Rich+Man%E2%80%99s+Daughter&cast=Shrine+Maiden&cast=Doctor&cast=Class+Rep&cast=Alien&cast=Pop+Idol&cast=Journalist&cast=Henchman&cast=Godly+Being&cast=Transfer+Student&incident=%7B%22day%22%3A1%2C%22incident%22%3A%22Confession%22%7D&incident=%7B%22day%22%3A2%2C%22incident%22%3A%22Confession%22%7D&incident=%7B%22day%22%3A3%2C%22incident%22%3A%22Confession%22%7D&incident=%7B%22day%22%3A4%2C%22incident%22%3A%22Confession%22%7D&incident=%7B%22day%22%3A5%2C%22incident%22%3A%22Confession%22%7D)

And what browser you are using?

**Comment by ChazKat** [comment]
Oh huh, I tried using this on my desktop and Chrome and Edge weren't giving any popups for generating a player aid. I'll try again later maybe.

I opened this on opera on my laptop and the site was functioning fine, that's odd.
________________________________

**Comment by LokiMidgard** [comment]
when you click on player aid, you should see 
![image](https://github.com/user-attachments/assets/df494931-c178-4c14-af9f-cd07e40b1695)

I mainly tested it in Brave, a Chrome browser, but in the past I also tested it in firefox

**Comment by LokiMidgard** [comment]
I will close this for now. If it is still a problem feel free to reopen it :)

**Comment by ChazKat** [comment]
Sorry for the late reply but this doesn't appear at all for any browsers on my desktop still, which is extremely weird.
________________________________

**Comment by LokiMidgard** [comment]
Interressting, I was now able to reproduce it....
A few days ago it worked....

**Comment by LokiMidgard** [comment]
Ok, try again, for some reason the check if share API can be used crashed and so the backup code was not executed.
Now this is also in a try..Catch block. So you should see the screenshoot.

**Comment by ChazKat** [comment]
Thank you, now this works again on all my devices! I'm excited to find people to play with when I leave for University this week.

Thanks,
Nicolas
________________________________
